import * as THREE from 'three';
import { PixelRenderer } from '../engine/pixelRenderer';
import { RESURRECT64, C } from '../engine/palette';
import { toon } from '../engine/toon';
import { Gafoop, Blorp } from '../art/gafoop';
import { Sheep } from '../art/sheep';

const canvas = document.getElementById('c') as HTMLCanvasElement;
const params = new URLSearchParams(location.search);
const pr = new PixelRenderer(canvas, 480, 270);
pr.setPalette(RESURRECT64);
pr.resize(innerWidth, innerHeight, 1);
const scene = new THREE.Scene();
scene.background = new THREE.Color(C.navy);
const sun = new THREE.DirectionalLight(0xffffff, 0.85);
sun.position.set(-3, 6, 5);
sun.castShadow = true;
Object.assign(sun.shadow.camera, { left: -4, right: 4, top: 4, bottom: -4 });
scene.add(sun, new THREE.HemisphereLight(0xffffff, 0x8899aa, 0.5));
const ground = new THREE.Mesh(new THREE.CircleGeometry(6, 24), toon(C.indigo));
ground.rotation.x = -Math.PI / 2;
ground.receiveShadow = true;
scene.add(ground);
const g = new Gafoop();
g.mouth = +(params.get('mouth') ?? 0.5);
if (params.has('point')) { g.armL.swing = 0.6; g.armL.curl = 0.1; }
g.update(0.1);
g.root.rotation.y = +(params.get('rot') ?? 0.35);
scene.add(g.root);
const b = new Blorp();
b.root.position.set(-1.6, 0, -0.4);
b.root.rotation.y = 0.5;
b.update(0.1);
scene.add(b.root);
const s = new Sheep(3);
s.root.position.set(1.5, 0, 0.2);
s.root.rotation.y = -0.6;
s.update();
scene.add(s.root);
for (const o of [g.root, b.root, s.root]) o.traverse((m) => { m.castShadow = true; });
const cam = new THREE.PerspectiveCamera(+(params.get('fov') ?? 32), 480 / 270, 0.1, 100);
cam.position.set(0, 1.4, 5.2);
cam.lookAt(0, 0.75, 0);
pr.post.depthAbs = 0.05;
pr.post.depthRel = 0.03;
pr.render(scene, cam);
